name: CoLM
tagline: CONFERENCE ON <br> LANGUAGE MODELING
date: October 2024
citation_date: May 2024
proceedings_title: Proceedings of the First COLM Conference
analytics: UA-
logo:
  image: static/images/logo.jpg
  width: 180px
  height: auto
# uncomment the following line to show the site title next to the logo image
# site_title: MiniConf
page_title:
  prefix: 'COLM 2024'
  separator: ': '
background_image: static/images/upenn.png
organization: COLM Organization Committee


# Configuration for auth
#Test user
#user: miniconf@miniconf.com
#pass: mIniconf1_

use_auth0:
auth0_client_id : JIdr6wi0z27LyLgwkJF0fpk700aj7MNH
auth0_domain : miniconf.auth0.com

calendar:
  colors: #  Colors for the different event hashtags:
    ---: '#bed972'
    qa: '#4FCAEB'
    talk: '#ccc'
  sunday_saturday: false  #  Include Sunday and Saturday
