# GitHub Actions workflow to build and deploy the COLM website to the gh-pages branch
# Trigger on pushes to the main branch (adjust if your default branch is named differently)
name: Deploy COLM Website

# Grant write permissions for contents so the action can push to gh-pages
permissions:
  contents: write

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repository (with credentials persisted for downstream steps)
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      # 2. Set up Python environment
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3. Install Node.js (for linting/tools if needed)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # 4. Install Python dependencies
      - name: Install Python dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          # If you need additional linting tools installed via npm, uncomment:
          # npm install

      # 5. Build the website
      - name: Build site
        run: |
          source venv/bin/activate
          make freeze

      # 6. Deploy to gh-pages branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages
          keep_files: false
